LOAD DATA
characterset UTF8
APPEND INTO TABLE lte_mrs_overcover_ana60
FIELDS TERMINATED BY ','
trailing nullcols
(
STARTTIME date "yyyy-mm-dd hh24:mi:ss",
ENDTIME date "yyyy-mm-dd hh24:mi:ss",
TIMESEQ,
MMEGROUPID,
MMEID,
ENODEBID,
CELLID,
TCELLID,
TCELLPCI,
TCELLFREQ,
RSRPDIFABS,
RSRPDIFCOUNT,
MRCOUNT,
CELLRSRPSUM,
CELLRSRPCOUNT,
TCELLRSRPSUM,
TCELLRSRPCOUNT,
ADJACENTAREAINTERFERENCEINTENS,
OVERLAPDISTURBRSRPDIFCOUNT,
ADJEFFECTRSRPCOUNT
)