#!/bin/bash
DB=$1
DBPATH=$2
WAREHOUSE="user/hive/warehouse/$DBPATH.db"

hive<<EOF
use $DB;
drop table tac_hour_http;
CREATE EXTERNAL TABLE tac_hour_http(
time                        string,
tac                         string,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/tac_hour_http';

drop table tac_day_http;
CREATE EXTERNAL TABLE tac_day_http(
time                        string,
tac                         string,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/tac_day_http';

drop table cell_hour_http;
CREATE EXTERNAL TABLE cell_hour_http(
time                        string,
cellid                      bigint,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/cell_hour_http';

drop table cell_day_http;
CREATE EXTERNAL TABLE cell_day_http(
time                        string,
cellid                      bigint,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/cell_day_http';


drop table sp_hour_http;
CREATE EXTERNAL TABLE sp_hour_http(
time                        string,
appserveripipv4             string,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/sp_hour_http';

drop table sp_day_http;
CREATE EXTERNAL TABLE sp_day_http(
time                        string,
appserveripipv4             string,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/sp_day_http';


drop table ue_hour_http;
CREATE EXTERNAL TABLE ue_hour_http(
time                        string,
imsi                        string,
msisdn                      string,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/ue_hour_http';


drop table ue_day_http;
CREATE EXTERNAL TABLE ue_day_http(
time                        string,
imsi                        string,
msisdn                      string,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/ue_day_http';

drop table imsi_cell_hour_http;
CREATE EXTERNAL TABLE imsi_cell_hour_http(
time                        string,
imsi                        string,
msisdn                      string,
cellid                      bigint,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/imsi_cell_hour_http';

drop table imsi_cell_day_http;
CREATE EXTERNAL TABLE imsi_cell_day_http(
time                        string,
imsi                        string,
msisdn                      string,
cellid                      bigint,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/imsi_cell_day_http';

drop table sgw_hour_http;
CREATE EXTERNAL TABLE sgw_hour_http(
time                        string,
sgwipaddr                   string,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/sgw_hour_http';

drop table sgw_day_http;
CREATE EXTERNAL TABLE sgw_day_http(
time                        string,
sgwipaddr                   string,
browsedownloadvisits       bigint,
videoservicevisits         bigint,
instantmessagevisits       bigint,
appvisits                  bigint,
browsedownloadbusiness     bigint,
videoservicebusiness       bigint,
instantmessagebusiness     bigint,
appbusiness                bigint,
dnsQuerySucc               bigint,
dnsQueryAtt                bigint,
tcpSetupSucc               bigint,
tcpSetupReq                bigint,
BearerULTCPRetransmit      bigint,
BearerULTCPTransmit        bigint,
BearerDLTCPRetransmit      bigint,
BearerDLTCPTransmit        bigint,
BearerULTCPMissequence     bigint,
BearerDLTCPMissequence     bigint,
pageresp                   bigint,
pagereq                    bigint,
pageresptimeall            bigint,
pageshowsucc               bigint,
pageshowtimeall            bigint,
httpdownflow               bigint,
httpdowntime               bigint,
mediasucc                  bigint,
mediareq                   bigint,
mediadownflow               double,
mediadowntime              bigint,
ServiceIMSucc              bigint,
ServiceIMReq               bigint,
readvisits                 bigint,
wbvisits                   bigint,
navigationvisits           bigint,
musicvisits                bigint,
gamevisits                 bigint,
payvisits                  bigint,
Animevisits                bigint,
mailvisits                 bigint,
p2pvisits                  bigint,
voipvisits                 bigint,
MultimediaMsgvisits        bigint,
financialvisits           bigint,
securityvisits             bigint,
shoppingvisits             bigint,
travelvisits               bigint,
cloudstoragevisits         bigint,
othervisits                bigint,
readbusiness               bigint,
wbbusiness                 bigint,
navigationbusiness         bigint,
musicbusiness              bigint,
gamebusiness               bigint,
paybusiness                bigint,
Animebusiness              bigint,
mailbusiness               bigint,
p2pbusiness                bigint,
voipbusiness               bigint,
MultimediaMsgbusiness      bigint,
financialbusiness          bigint,
securitybusiness           bigint,
shoppingbusiness           bigint,
travelbusiness             bigint,
cloudstoragebusiness       bigint,
otherbusiness              bigint,
mediaRespTimeall           bigint,
mediaResp                  bigint,
ServiceIMTrans             bigint,
ServiceIMFlow               double,
ServiceIMTime              bigint
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/sgw_day_http';

drop table warnningtable;
CREATE EXTERNAL TABLE warnningtable(
City  int,
Cellid   bigint,
warnningtitle    string,
warnningtime     string,
effect           string
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/warnningtable';

drop table t_xdr_event_msg;
CREATE EXTERNAL TABLE t_xdr_event_msg(
city string,
xdrid string,
procedurestarttime bigint,
ttime string,
procedureendtime bigint,
imsi string,
imei string,
tetac string,
msisdn string,
cellid bigint,
sgw string,
sp string,
apptype int,
appsubtype int,
appstatus int,
etype string,
failurecase string,
cellregion string
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/t_xdr_event_msg';


drop table LTECELL;
create table LTECELL(
  MCC         int,
  MNC         INT,
  MMEGROUPID  INT,
  MMEID       int,
  ENODEBID    int,
  SITENAME    STRING,
  CELLNAME    STRING,
  LOCALCELLID int,
  CELLID      int,
  TAI         INT,
  PCI         INT,
  FREQ1       INT,
  FREQ2       INT,
  BANDWIDTH1  double,
  BANDWIDTH2  double,
  FREQCOUNT   INT,
  LONGITUDE   double,
  LATITUDE    double,
  SECTORTYPE  int,
  DOORTYPE    INT,
  TILTTOTAL   DOUBLE,
  TILTM       DOUBLE,
  TILTE       DOUBLE,
  AZIMUTH     DOUBLE,
  BEAMWIDTH   DOUBLE,
  VBEAMWIDTH  DOUBLE,
  AHEIGHT     DOUBLE,
  CITY        string,
  COMPANY     string,
  REGION      string,
  ENBTYPE     string,
  ENBVERSION  string
  )ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ',';

drop table business_type_detail;
create EXTERNAL table business_type_detail(
        TTIME              string,
        city               string,
        region             string,
        CELLID             int,
        app_type           string,
        app_sub_type       string,
        uldata             bigint,
        dldata             bigint
)
PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/business_type_detail';
EOF